cmake_minimum_required(VERSION 3.16)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED true)

project(rover VERSION 1.0)
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-Wall")
set(CMAKE_CXX_FLAGS "-g -O0 ")

set(ROOT_DIR        ./                      )
set(INIT_DIR        ${ROOT_DIR}/0_init      )
set(PRIMARY_DIR     ${ROOT_DIR}/1_primary   )
set(SECONDARY_DIR   ${ROOT_DIR}/2_secondary )
set(AUXILIARY_DIR   ${ROOT_DIR}/3_auxiliary )
set(DIAGNOSTIC_DIR  ${ROOT_DIR}/4_diagnostic)
set(CFG_DIR         ${ROOT_DIR}/5_cfg       )
set(COMMON_DIR      ${ROOT_DIR}/6_common    )
set(LIBRARY_DIR     ${ROOT_DIR}/7_lib       )

add_executable(${PROJECT_NAME} "${INIT_DIR}/init/init.cpp")


# add_subdirectory("lib")
add_subdirectory(       ${INIT_DIR}/SWC_ThreadMgr )
add_subdirectory( ${DIAGNOSTIC_DIR}/SWC_Logger    )
add_subdirectory( ${DIAGNOSTIC_DIR}/SWC_StatMon   )
add_subdirectory(    ${LIBRARY_DIR}/NCurses       )
add_subdirectory(    ${LIBRARY_DIR}/WiringPi      )
add_subdirectory(    ${PRIMARY_DIR}/SWC_Veh       )
add_subdirectory(    ${PRIMARY_DIR}/SWC_Pwtr      )
add_subdirectory(    ${PRIMARY_DIR}/SWC_StSys     )
add_subdirectory(    ${PRIMARY_DIR}/SWC_Input     )
add_subdirectory(     ${COMMON_DIR}/PWMChannel    )
add_subdirectory(     ${COMMON_DIR}/PeriodicCall  )
add_subdirectory(     ${COMMON_DIR}/DelayedCall   )
add_subdirectory(  ${SECONDARY_DIR}/SWC_Buzzer    )
add_subdirectory(  ${SECONDARY_DIR}/SWC_Tacho     )
add_subdirectory(  ${SECONDARY_DIR}/SWC_Fan       )
add_subdirectory(  ${AUXILIARY_DIR}/SWC_PadInput  )
# add_subdirectory("app/pwr_mon")
# add_subdirectory("drv/i2c")
# add_subdirectory("drv/light_ctrl")
# add_subdirectory("drv/tacho")
# add_subdirectory("drv/steer_sys")

target_link_libraries(${PROJECT_NAME}  PUBLIC pthread        )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_ThreadMgr  )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Logger     )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_StatMon    )
target_link_libraries(${PROJECT_NAME}  PUBLIC NCurses        )
target_link_libraries(${PROJECT_NAME}  PUBLIC WiringPi       )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Veh        )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Pwtr       )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_StSys      )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Input      )
target_link_libraries(${PROJECT_NAME}  PUBLIC PWMChannel     )
target_link_libraries(${PROJECT_NAME}  PUBLIC DelayedCall    )
target_link_libraries(${PROJECT_NAME}  PUBLIC PeriodicCall   )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Buzzer     )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Tacho      )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_Fan        )
target_link_libraries(${PROJECT_NAME}  PUBLIC SWC_PadInput   )
# target_link_libraries(${PROJECT_NAME} PUBLIC lib)
# target_link_libraries(${PROJECT_NAME} PUBLIC dummy_app)
# target_link_libraries(${PROJECT_NAME} PUBLIC i2c)
# target_link_libraries(${PROJECT_NAME} PUBLIC light_ctrl)
# target_link_libraries(${PROJECT_NAME} PUBLIC tacho)
# target_link_libraries(${PROJECT_NAME} PUBLIC pwr_mon)
# target_link_libraries(${PROJECT_NAME} PUBLIC steer_sys)
# target_link_libraries(${PROJECT_NAME} PUBLIC fan_ctrl)
# target_link_libraries(${PROJECT_NAME} PUBLIC buzzer)

target_include_directories(${PROJECT_NAME} PUBLIC 
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${PRIMARY_DIR}/SWC_ThreadMgr/cfg
)